### ISSUE TITLE
PUA Q7 defect from UAT

### ISSUE THREAD

**Issue by mthong** [cagov/unemployment#400] opened 2020-06-26 06:00 UTC
A test user at EDD noticed that they could submit the PUA form without actually selecting an option from the radio button. It was sufficient to simply select the "Yes" answer but not one of the options that then appears. 

This was replicated by me. 

I'm not sure if this is related to or the same as #391.

**Comment by kalvinwang** [comment] 2020-06-26 20:18
This is a duplicate of #391 which has been resolved

**Closed by kalvinwang** 2020-06-26 20:18 UTC
Labels: initiative: certification, uat
