### ISSUE TITLE
Spanish links should direct to Spanish EDD pages

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#199] opened 2020-05-14 20:07 UTC
Right now, if a Spanish user clicks on a link in the guide, it will direct them to the English version of the expected page. We should update the links to go to the Spanish version. 

https://docs.google.com/document/d/160ZmesUtMzUCTIk-nXEFANQnjqt-WBa3GbuCfkybVWg/edit

**Comment by kalvinwang** [comment] 2020-05-15 14:22
@sharonwarner this seems like a bug (not a regression, but we weren't committing to being part of the Spanish flow then either), and I think it can be fixed in an hour. Create new strings in translation.js for unique links, and pass them in as props to each Trans component that contains a string, e.g. `<Trans t={t} i18nKey="tab0-list5-item1" link="{t("stringKey")}"><a href="{{link}}">etc</a></Trans>`... do you think it might be worse than that?

**Comment by sharonwarner** [comment] 2020-05-15 14:38
@kalvinwang That general plan sounds good, but I think it will take longer than an hour. We have a lot of links that we'd need to update and manually test. Michelle confirmed that it's fine to launch the Spanish pages as is, so I think we should hold on this until we've completed at least the high-priority existing sprint work.

**Comment by kalvinwang** [comment] 2020-05-15 21:19
(Talked to Sharon and did this ticket since the high-priority existing tickets were blocked for varying reasons)

**Closed** 2020-05-18 14:40 UTC
Labels: pts: 2, type: engineering
