### ISSUE TITLE
Reloading always navigates back to the first tab

### ISSUE THREAD

**Issue by idealisms** [cagov/unemployment#155] opened 2020-05-07 17:11 UTC
Routing was added in issue #102 , but I had added code to redirect all pages to /guide.

The redirect shouldn't trigger if the user is on one of the tabs.

**Comment by sharonwarner** [comment] 2020-05-07 17:25
Duplicate of https://github.com/cagov/unemployment/issues/130

**Closed** 2020-05-07 21:28 UTC
Labels: type: engineering
